[package]
name = "l3"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13.1", features = ["blocking", "json", "native-tls"] }
rand = "0.9.2"
once_cell = "1.21"
hex = "0.4"
